collect_garbage:
  target:
    entity:
      integration: garbage_collection
      domain: sensor
  fields:
    last_collection:
      example: "2020-08-16 10:54:00"
      selector:
        datetime:
update_state:
  target:
    entity:
      integration: garbage_collection
      domain: sensor
add_date:
  target:
    entity:
      integration: garbage_collection
      domain: sensor
  fields:
    date:
      required: true
      example: "2020-08-16"
      selector:
        date:
remove_date:
  target:
    entity:
      integration: garbage_collection
      domain: sensor
  fields:
    date:
      required: true
      example: "2020-08-16"
      selector:
        date:
offset_date:
  target:
    entity:
      integration: garbage_collection
      domain: sensor
  fields:
    date:
      required: true
      example: "2020-08-16"
      selector:
        date:
    offset:
      required: true
      example: 1
      selector:
        number:
          min: -31
          max: 31
          mode: box
