name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set version number"
        run: |
          sed -i '/  "version": /c\  "version": "${{ github.ref_name }}",' custom_components/garbage_collection/manifest.json
      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP garbage_collection Dir
        run: |
          cd "${{ github.workspace }}/custom_components/garbage_collection"
          zip garbage_collection.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/garbage_collection/garbage_collection.zip
          asset_name: garbage_collection.zip
          tag: ${{ github.ref }}
          overwrite: true
